# Generated by Django 5.1.1 on 2024-12-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_load_approve_transaction_loan_approve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal'), (3, 'Loan'), (4, 'Loan Paid'), (5, 'Transfers Balance')], null=True),
        ),
    ]
