# Generated by Django 5.1.1 on 2024-12-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_account_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account_no',
            field=models.IntegerField(null=True),
        ),
    ]
