# Generated by Django 5.1.1 on 2024-12-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_account_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
